### ISSUE TITLE
Rollup 2.10

### ISSUE THREAD

**Issue by dilyanpalauzov** [juliendargelos/rollup-plugin-html-minifier#1]
Installing `rollup-plugin-html-minifier` prints the message that it has incorrect peer dependency `rollup@^1.21.1`.  I use rollup 2.

* Update the dependencies, so that rollup-plugin-html-minifier works wtth rollup 2.10.

**Comment by juliendargelos** [comment]
Thanks for opening this issue, I will take a look very soon.

**Comment by juliendargelos** [comment]
The plugin has been published with the updated rollup peer dependency
