### ISSUE TITLE
Insert rollup-plugin-html-minifier in the “awesome list”

### ISSUE THREAD

**Issue by dilyanpalauzov** [juliendargelos/rollup-plugin-html-minifier#3]
Include rollup-plugin-html-minifier in the list at https://github.com/rollup/awesome/blob/master/README.md

**Comment by juliendargelos** [comment]
I first have to add tests to this plugin, which I'll do as soon as possible.

**Comment by juliendargelos** [comment]
The addition has been requested: https://github.com/rollup/awesome/pull/89

**Comment by juliendargelos** [comment]
The plugin is now listed in awesome rollup.
